# Generated by Django 4.1.7 on 2023-03-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
