# Generated by Django 4.1.7 on 2023-05-01 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0005_userpost_image_alter_userpost_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=models.ImageField(upload_to='upload/'),
        ),
    ]
